fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\FosUser
  from_email:
    address: "cata@yahoo.com"
    sender_name: "catapostman"
  service:
    mailer: 'fos_user.mailer.noop'
    # mailer: 'fos_user.mailer.twig_swift' # Works as well